# Generated by Django 4.2.5 on 2023-09-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Greeting', 'Greeting'), ('Closing', 'Closing'), ('User Name', 'User Name'), ('User Email', 'User Email'), ('Case Number', 'Case Number'), ('Agent Name', 'Agent Name'), ('Coordinator Choices', 'Coordinator Choices'), ('Coordinator Choices Abbreviated', 'Coordinator Choices Abbreviated'), ('Coordinator Name', 'Coordinator Name'), ('Coordinator Email', 'Coordinator Email'), ('Coordinator Phone', 'Coordinator Phone'), ('Incorrect EK', 'Incorrect EK'), ('Correct EK', 'Correct EK'), ('School Year', 'School Year'), ('Results ID', 'Results ID'), ('Signature', 'Signature'), ('Internal Teams', 'Internal Teams')], max_length=60)),
                ('label_two', models.CharField(blank=True, max_length=30, null=True)),
                ('field_type', models.CharField(choices=[('ChoiceField', 'ChoiceField'), ('IntegerField', 'IntegerField'), ('CharField', 'CharField'), ('EmailField', 'EmailField'), ('TextField', 'TextField'), ('EKField', 'EKField')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFormSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_name', models.CharField(default='Signature', max_length=100)),
                ('signature_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('template_text', models.TextField()),
                ('field_order_config', models.JSONField(blank=True, null=True)),
                ('fields', models.ManyToManyField(blank=True, to='email_tool.customformfield')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project Name', max_length=40)),
                ('global_project', models.BooleanField(default=False)),
                ('email_templates', models.ManyToManyField(blank=True, related_name='projects_using_templates', to='email_tool.customformtemplate')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_using_templates', to='email_tool.customformsignature')),
            ],
        ),
        migrations.AddField(
            model_name='customformtemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='email_tool.project'),
        ),
        migrations.AddField(
            model_name='customformsignature',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='email_tool.project'),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects_using_fields', to='email_tool.project'),
        ),
    ]
