# Generated by Django 4.2.5 on 2023-09-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customformfield',
            name='projects',
        ),
        migrations.AddField(
            model_name='customformfield',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_using_fields', to='email_tool.project'),
        ),
    ]
