# Generated by Django 4.2.5 on 2023-09-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0002_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_template',
            field=models.ForeignKey(default='Texas', on_delete=django.db.models.deletion.CASCADE, to='email_tool.emailtemplate'),
        ),
    ]
