# Generated by Django 4.2.5 on 2023-09-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0003_customformfield_template_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='template_code',
            field=models.CharField(blank=True, default='', max_length=61),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='template_format',
            field=models.CharField(blank=True, default='', max_length=62),
        ),
    ]
