# Generated by Django 4.2.5 on 2023-09-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0004_alter_project_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_tool.emailtemplate'),
        ),
    ]
