# Generated by Django 4.2.5 on 2023-09-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0005_alter_project_email_template'),
    ]

    operations = [
    ]
