# Generated by Django 4.2.5 on 2023-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0005_customformtemplate_template_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='signature',
            field=models.TextField(default='Signature Goes Here', max_length=400, null=True),
        ),
    ]
