# Generated by Django 4.2.5 on 2023-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0006_alter_project_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='label',
            field=models.CharField(max_length=60),
        ),
    ]
