# Generated by Django 4.2.5 on 2023-09-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0006_auto_20230909_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email_template',
        ),
    ]
