# Generated by Django 4.2.5 on 2023-09-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0007_remove_project_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='email_tool.emailtemplate'),
            preserve_default=False,
        ),
    ]
