# Generated by Django 4.2.5 on 2023-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0008_project_form_fields_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='label_two',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
