# Generated by Django 4.2.5 on 2023-09-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0008_project_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
