# Generated by Django 4.2.5 on 2023-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0009_alter_customformfield_label_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='label_two',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
