# Generated by Django 4.2.5 on 2023-09-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0009_emailtemplate_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template_name',
        ),
    ]
