# Generated by Django 4.2.5 on 2023-09-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0010_remove_emailtemplate_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_signature',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
