# Generated by Django 4.2.5 on 2023-09-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0011_project_project_signature_project_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email_template',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_signature',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_title',
        ),
        migrations.AddField(
            model_name='project',
            name='clear_cache_and_cookies_email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clear_cache_and_cookies', to='email_tool.emailtemplate'),
        ),
        migrations.AddField(
            model_name='project',
            name='no_tide_email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_tide', to='email_tool.emailtemplate'),
        ),
    ]
