# Generated by Django 4.2.5 on 2023-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0012_remove_project_email_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clear_cache_and_cookies_email_template',
        ),
        migrations.RemoveField(
            model_name='project',
            name='no_tide_email_template',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_page',
            field=models.CharField(default='home', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='email_templates',
            field=models.ManyToManyField(to='email_tool.emailtemplate'),
        ),
    ]
