# Generated by Django 4.2.5 on 2023-09-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0013_remove_project_clear_cache_and_cookies_email_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='important_dates',
            field=models.ManyToManyField(to='email_tool.importantdates'),
        ),
    ]
