# Generated by Django 4.2.5 on 2023-09-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0014_importantdates_project_important_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='important_dates',
        ),
        migrations.AddField(
            model_name='project',
            name='important_dates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_tool.importantdates'),
        ),
    ]
