# Generated by Django 4.2.5 on 2023-09-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0015_remove_project_important_dates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('greeting', 'Greeting'), ('closing', 'Closing')], max_length=20)),
                ('field_type', models.CharField(max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(choices=[('Hello', 'Hello'), ('Greetings', 'Greetings'), ('Good Morning', 'Good Morning'), ('Good Afternoon', 'Good Afternoon'), ('Good Evening', 'Good Evening')], max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='important_dates',
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImportantDates',
        ),
        migrations.AddField(
            model_name='customformfield',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_tool.project'),
        ),
    ]
