# Generated by Django 4.2.5 on 2023-09-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0017_alter_customformfield_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='choices',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_type',
            field=models.CharField(choices=[('ChoiceField', 'ChoiceField'), ('IntegerField', 'IntegerField'), ('CharField', 'CharField'), ('EmailField', 'EmailField')], max_length=20),
        ),
    ]
