# Generated by Django 4.2.5 on 2023-09-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0018_alter_customformfield_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customformfield',
            name='project',
        ),
        migrations.CreateModel(
            name='CustomFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(blank=True, to='email_tool.customformfield')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_tool.project')),
            ],
        ),
    ]
