# Generated by Django 4.2.5 on 2023-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0019_remove_customformfield_project_customformtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformfield',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
