# Generated by Django 4.2.5 on 2023-09-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0020_customformfield_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='title',
            field=models.CharField(choices=[('All Projects', 'All Projects'), ('Indiana', 'Indiana'), ('MAAC2-hawaii', 'MAAC2 - Hawaii'), ('MAAC2-idaho', 'MAAC2 - Idaho'), ('MAAC2-washington', 'MAAC2 - Washington'), ('Ohio', 'Ohio'), ('Texas', 'Texas')], max_length=100),
        ),
    ]
