# Generated by Django 4.2.5 on 2023-09-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0021_delete_greeting_alter_customformfield_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_page',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='custom_form_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='email_tool.customformtemplate'),
            preserve_default=False,
        ),
    ]
