# Generated by Django 4.2.5 on 2023-09-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0022_remove_emailtemplate_html_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='label',
            field=models.CharField(choices=[('Greeting', 'Greeting'), ('Closing', 'Closing'), ('User Name', 'User Name'), ('User Email', 'User Email'), ('Case Number', 'Case Number'), ('Agent Name', 'Agent Name'), ('Coordinator Choices', 'Coordinator Choices'), ('Coordinator Name', 'Coordinator Name'), ('Coordinator Email', 'Coordinator Email'), ('Coordinator Phone', 'Coordinator Phone')], max_length=20),
        ),
    ]
