# Generated by Django 4.2.5 on 2023-09-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0024_remove_customformtemplate_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customformtemplate',
            name='template_text',
        ),
    ]
