# Generated by Django 4.2.5 on 2023-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0027_alter_project_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformtemplate',
            name='project_name',
            field=models.CharField(choices=[('indiana', 'Indiana'), ('maac2-hawaii', 'MAAC2 - Hawaii'), ('maac2-idaho', 'MAAC2 - Idaho'), ('maac2-washington', 'MAAC2 - Washington'), ('ohio', 'Ohio'), ('texas', 'Texas')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='email_templates',
            field=models.ManyToManyField(blank=True, to='email_tool.customformtemplate'),
        ),
    ]
