# Generated by Django 4.2.5 on 2023-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0028_customformtemplate_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformfield',
            name='label_two',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
