# Generated by Django 4.2.5 on 2023-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0029_customformfield_label_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformtemplate',
            name='field_order_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
