# Generated by Django 4.2.5 on 2023-09-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0030_customformtemplate_field_order_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='field_type',
            field=models.CharField(choices=[('ChoiceField', 'ChoiceField'), ('IntegerField', 'IntegerField'), ('CharField', 'CharField'), ('EmailField', 'EmailField'), ('TextField', 'TextField'), ('EKField', 'EKField')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='label',
            field=models.CharField(choices=[('Greeting', 'Greeting'), ('Closing', 'Closing'), ('User Name', 'User Name'), ('User Email', 'User Email'), ('Case Number', 'Case Number'), ('Agent Name', 'Agent Name'), ('Coordinator Choices', 'Coordinator Choices'), ('Coordinator Choices Abbreviated', 'Coordinator Choices Abbreviated'), ('Coordinator Name', 'Coordinator Name'), ('Coordinator Email', 'Coordinator Email'), ('Coordinator Phone', 'Coordinator Phone'), ('Incorrect EK', 'Incorrect EK'), ('Correct EK', 'Correct EK'), ('School Year', 'School Year'), ('Results ID', 'Results ID')], max_length=60),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='title',
            field=models.CharField(choices=[('All Projects', 'All Projects'), ('Indiana', 'Indiana'), ('hawaii', 'Hawaii'), ('idaho', 'Idaho'), ('washington', 'Washington'), ('Ohio', 'Ohio'), ('Texas', 'Texas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customformtemplate',
            name='project_name',
            field=models.CharField(choices=[('indiana', 'Indiana'), ('hawaii', 'Hawaii'), ('idaho', 'Idaho'), ('washington', 'Washington'), ('ohio', 'Ohio'), ('texas', 'Texas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(choices=[('indiana', 'Indiana'), ('hawaii', 'Hawaii'), ('idaho', 'Idaho'), ('washington', 'Washington'), ('ohio', 'Ohio'), ('texas', 'Texas')], max_length=100),
        ),
    ]
