# Generated by Django 4.2.5 on 2023-09-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0031_alter_customformfield_field_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFormSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(choices=[('indiana', 'Indiana'), ('hawaii', 'Hawaii'), ('idaho', 'Idaho'), ('washington', 'Washington'), ('ohio', 'Ohio'), ('texas', 'Texas')], max_length=100)),
                ('signature_name', models.CharField(default='Signature', max_length=100)),
                ('signature_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
