# Generated by Django 4.2.5 on 2023-09-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0032_customformsignature_delete_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformtemplate',
            name='signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='email_tool.customformsignature'),
            preserve_default=False,
        ),
    ]
