# Generated by Django 4.2.5 on 2023-09-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0033_customformtemplate_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customformsignature',
            name='signature_text',
        ),
        migrations.AddField(
            model_name='project',
            name='signature_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
