# Generated by Django 4.2.5 on 2023-09-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_tool', '0034_remove_customformsignature_signature_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customformtemplate',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='project',
            name='signature_text',
        ),
        migrations.AddField(
            model_name='customformsignature',
            name='signature_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='email_tool.customformsignature'),
            preserve_default=False,
        ),
    ]
